### PR TITLE
Windows toil, including complete excision of POSIX memstreams

### PR DESCRIPTION
**Pull request by dankamongmen**
With this, we successfully link `notcurses-core.dll`, `norcurses.dll`, and `notcurses-info` on MSYS2, closing #463. It's a gigantic and varied change, though it seems to be working reasonably well for such a massive overhaul done over the course of a single night, heh. Foremost among the serious changes is the complete removal of POSIX memstreams, of which we made use fairly extensively, closing #1977. This is a first draft of `fbuf`, very trivial. It knocks us down from 192s to 204s on my workstation for a complete `notcurses-demo` run, almost entirely due to excessive page reservations, so we'll want to address that prior to merge. This does not get everything working on Windows by a long shot, but it does get a minimal binary linked, which constitutes "becoming something on windows" (#463). We'll progress iteratively from here.

Thanks to @michaelsbradleyjr for contributing greatly to making this happen!

### CODE REVIEW

**Review by michaelsbradleyjr — COMMENTED** [review]
I built this branch (as far as it goes) on my Windows 10 laptop, and have `build/notcurses-info.exe` as described.

Seems very promising, great work!

**Comment by dankamongmen** [comment]
So the 192s vs 204s i quoted is more like 200s vs 204s. The 192s figure was prior to adding deflate compression to kitty, which greatly speeds up the networked case but slows down the local case a bit, for now. So the slowdown isn't that big a deal, something on the order of 2%. We can get that back.

**Comment by dankamongmen** [comment]
we're closer now, after cutting a few binaries out of the Windows build. we're running into this:

```
D:/a/_temp/msys/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/notcurses++.dir/objects.a(Plane.cc.obj):Plane.cc:(.text$_ZN4ncpp5Plane9map_planeEP7ncplanePS0_+0x189): undefined reference to `__stack_chk_fail'
593
D:/a/_temp/msys/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/notcurses++.dir/objects.a(Plane.cc.obj):Plane.cc:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
594
D:/a/_temp/msys/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/notcurses++.dir/objects.a(Tablet.cc.obj):Tablet.cc:(.text$_ZN4ncpp8NcTablet10map_tabletEP8nctabletPNS_9NotCursesE+0x189): undefined reference to `__stack_chk_fail'
```

also, i can't successfully run any binaries. some get runtime loader failures about `libwinpthreads`, some crash immediately, and one (`sgr-direct`) almost seems to start up. so we're close.

**Comment by dankamongmen** [comment]
> I built this branch (as far as it goes) on my Windows 10 laptop, and have `build/notcurses-info.exe` as described.

are you able to run `notcurses-info`? i get a failure attempting to link in `api-ms-win-crt-private...dll`.

we're running into this `__stack_chk` thing when trying to link a few things right now.

i think i might go ahead and merge this, getting us closer to where we need to be...but there will still be quite a bit of work to do on windows.

**Comment by michaelsbradleyjr** [comment]
> are you able to run `notcurses-info`? i get a failure attempting to link in `api-ms-win-crt-private...dll`.

Oops, I missed this earlier, sorry for the slow reply.

I didn't get an error message when running it in UCRT64 mintty, but it did nothing (no output) and exited with error code `1`.

When running it in Windows Terminal (`cmd.exe`) in the `build/` dir, I got an error about a DLL. So I copied the built `.dll` and `notcurses-info.exe` to `C:\ucrt64\ucrt64\bin\`. I then ran in the latter; there was no longer an error about a DLL, but there was no output.

Before copying stuff to `C:\ucrt64\ucrt64\bin\` and running from there, I tried `set PATH=C:\ucrt64\ucrt64\bin;%PATH%` but it didn't resolve the problem with finding the needed DLL/s. I don't know why that didn't work, usually does.

**Comment by WSLUser** [comment]
`api-ms-win-crt-private...dll`

This comes from the Windows SDK. Is that being used at all? I don't think Mintty messes with Windows SDK at all and rolls their own thing. I mentioned before how they have a bunch of hackery, this would be a perfect example. I think they use a different crypto library than the one used natively by Windows. Understandable as there are some limitations with it.

**Comment by michaelsbradleyjr** [comment]
Another way to get around the missing DLL would be to pass `-static` to the compiler/linker. Whether static linking is desired for e.g. `notcurses-info.exe` is another question.

I'll give it a shot and report back.

**Comment by dankamongmen** [comment]
alright, time to start merging this bad boy back in.

**Comment by dankamongmen** [comment]
fuck it, let's do it!

**Comment by dankamongmen** [comment]
alright. we're now kinda working in the MSYS2 environment. we're not quite working in Windows Terminal proper yet, but i think i know how to get us there.

at this point we could very much use some testing and enumeration of broken areas. compiler warnings will likely point to some of these. it's not yet ready to hand off to vcpkg or nuget, but we're getting there.

**Comment by WSLUser** [comment]
Making private packages on here for testing would be nice so we don't have to continue building. You should be able to generate artifacts from the CI/CD pipeline at least.

**Comment by dankamongmen** [comment]
> Making private packages on here for testing would be nice so we don't have to continue building. You should be able to generate artifacts from the CI/CD pipeline at least.

PRs are always welcome!

**Pull request merged**
