### PR TITLE
Add ncvisual_from_rgb_{packed, loose}()

### LINKED ISSUE #1767: New function ncvisual_from_rgb
I belive it would be very handy to have an `ncvisual_from_rgb()` function to read rgb data from a buffer without the alpha byte, and apply the same alpha to all pixels, through an additional argument. With a signature like:

```c
API ALLOC struct ncvisual* ncvisual_from_rgb(const void* rgb, int rows,
                                              int rowstride, int cols, unsigned char alpha);
```

I'm encountering the case where having to interface with the output of other libraries that doesn't deal with alpha makes it somewhat cumbersome.

And maybe in that case it should also be added `ncvisual_from_bgr` for completion?

### PR DESCRIPTION
**Pull request by dankamongmen**
Add `ncvisual_from_rgb_packed()` and `ncvisual_from_rgb_loose()`, plus unit tests. Closes #1767.

### CODE REVIEW

**Comment by joseluis** [comment]
@dankamongmen hey man, isn't the  _packed & _loose behaviour reversed in respect to `ncblit_rgb_packed` & `ncblit_rgb_loose`?

I mean, for `ncvisual_from_rgb_loose` "pixels are 3-byte RGB." and in `ncblit_rgb_loose` "linesize must be a multiple of 4 for this RGBx data.", meanwhile for `ncvisual_from_rgb_packed` "the pixels are 4-byte RGBx."...

**Comment by joseluis** [comment]
yeah, I'm pretty sure the names have to be reversed, since packed must mean that all the pixel data is placed next to each other without gaps in memory...

**Comment by joseluis** [comment]
Ah, the good news is that apparently the only thing reversed are the doc comments, so I can fix that.

**Comment by dankamongmen** [comment]
nice catch! thanks!

**Pull request merged**
