### PR TITLE
* remove cpp headers and other c++ support file from installation if …

### PR DESCRIPTION
**Pull request by mulle-nat**
…USE_CXX is not set

### CODE REVIEW

**Comment by mulle-nat** [comment]
I already had a pull request like this, but this one is better. Now pkgconfig and cmake files are also not installed, if there is no c++ support.

**Comment by dankamongmen** [comment]
I'm not sure I like this idea. What's your motivation here? `USE_CXX` is all about not requiring a C++ compiler when building Notcurses. Installing the C++ headers doesn't require a C++ compiler for people building against Notcurses who aren't using C++. What's the point of not installing the C++ headers?

I definitely don't think this ought disable pkgconfig/CMake support, independently of your answer to the previous question.

**Comment by mulle-nat** [comment]
If you don't have a C++ compiler on your system and you can't build the c++ library, why would you want to install the headers or cmake/pkgconfig files supporting that ? You'd rather fail at compile time than link time. I really fail to see your argument here.

Anway, this patch also corrects  the C headers like `notcurses/notcurses.h` **not** being installed, when `-DUSE_CXX=OFF`.
Here's the diff of two installs with your current github version once with `-DUSE_CXX=OFF` and once with `-DUSE_CXX=ON`.

``` sh
1a2,42
> ├── include
> │   ├── ncpp
> │   │   ├── Cell.hh
> │   │   ├── CellStyle.hh
> │   │   ├── Direct.hh
> │   │   ├── _exceptions.hh
> │   │   ├── FDPlane.hh
> │   │   ├── _flag_enum_operator_helpers.hh
> │   │   ├── _helpers.hh
> │   │   ├── internal
> │   │   │   └── Helpers.hh
> │   │   ├── Menu.hh
> │   │   ├── MultiSelector.hh
> │   │   ├── NCAlign.hh
> │   │   ├── NCBox.hh
> │   │   ├── NCKey.hh
> │   │   ├── NCLogLevel.hh
> │   │   ├── ncpp.hh
> │   │   ├── NotCurses.hh
> │   │   ├── Palette.hh
> │   │   ├── Pile.hh
> │   │   ├── Plane.hh
> │   │   ├── Plot.hh
> │   │   ├── Progbar.hh
> │   │   ├── Reader.hh
> │   │   ├── Reel.hh
> │   │   ├── Root.hh
> │   │   ├── Selector.hh
> │   │   ├── Subproc.hh
> │   │   ├── TabletCallback.hh
> │   │   ├── Tablet.hh
> │   │   ├── Utilities.hh
> │   │   ├── Visual.hh
> │   │   └── Widget.hh
> │   └── notcurses
> │       ├── direct.h
> │       ├── nckeys.h
> │       ├── ncport.h
> │       ├── ncseqs.h
> │       ├── notcurses.h
> │       └── version.h
12a54
> │   ├── libnotcurses++.a
20a63
> │   ├── libnotcurses++.so -> libnotcurses++.so.3
21a65
> │   ├── libnotcurses++.so.3 -> libnotcurses++.so.3.0.9
22a67
> │   ├── libnotcurses++.so.3.0.9
38c83
< 9 directories, 26 files
---
> 13 directories, 67 files
```

**Comment by dankamongmen** [comment]
confirmed `USE_CXX=no` results in no headers installed

**Comment by dankamongmen** [comment]
also, despite `USE_CXX=no`, we're using c++:

```
/usr/bin/cmake -E cmake_link_script CMakeFiles/notcurses.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -O2 -g -DNDEBUG -shared -Wl,-soname,libnotcurses.so.3 -o libnotcurses.so.3.0.9 CMakeFiles/notcurses.dir/src/media/ffmpeg.c.o CMakeFiles/notcurses.dir/src/media/none.c.o "CMakeFiles/notcurses.dir/src/media/oiio-indep.c.o" CMakeFiles/notcurses.dir/src/media/oiio.cpp.o CMakeFiles/notcurses.dir/src/media/shim.c.o CMakeFiles/notcurses.dir/src/compat/compat.c.o   -L/usr/local/lib  -Wl,-rpath,/usr/local/lib:/home/dank/src/dankamongmen/notcurses/build: libnotcurses-core.so.3.0.9 -lavcodec -lm -llzma -lz -lswresample -lavutil -lva-drm -lva-x11 -lvdpau -lm -ldrm -lva -latomic -lX11 -lavdevice -lxcb -lxcb-shm -lxcb-shape -lxcb-xfixes -lasound -lSDL2 -lsndio -lXv -lXext -lavfilter -lm -lm -lm -lswscale -lavformat -lbz2 -lm -lavcodec -lm -llzma -lz -lswresample -lavutil -lva-drm -lva-x11 -lvdpau -lm -ldrm -lva -latomic -lX11 -lavformat -lbz2 -lavcodec -lm -llzma -lz -lswresample -lavutil -lva-drm -lva-x11 -lvdpau -lm -ldrm -lva -latomic -lX11 -lswscale -lavutil -lva-drm -lva-x11 -lvdpau -lm -ldrm -lva -latomic -lX11 -lavutil -lva-drm -lva-x11 -lvdpau -lm -ldrm -lva -latomic -lX11 /usr/lib/x86_64-linux-gnu/librt.a -lavdevice -lxcb -lxcb-shm -lxcb-shape -lxcb-xfixes -lasound -lSDL2 -lsndio -lXv -lXext -lavfilter 
```

**Comment by dankamongmen** [comment]
why are we building oiio code at all?

```
[ 47%] Building CXX object CMakeFiles/notcurses.dir/src/media/oiio.cpp.o
```

**Comment by mulle-nat** [comment]
Currently when `USE_CXX` is `OFF` your  `CMakeLists.txt` takes great pains not to compile any C++ specific `.cpp` files. Therefore it won't produce or install `libnotcurses++.a` for example (as seen in above diff). 
Then I come in and say: Installing headers or other support files for a non-existing library is a bug.

Building the notcurses library as C++ (with mangling) wouldn't even work IMO, because you're exporting all your symbols as C with:

``` c
"#ifdef __cplusplus
extern "C" {
#endif. 
```

The current `CMakeLists.txt` is fine, it just needs these fixes :wink:

**Comment by dankamongmen** [comment]
> If you don't have a C++ compiler on your system and you can't build the c++ library, why would you want to install the headers or cmake/pkgconfig files supporting that ? You'd rather fail at compile time than link time. I really fail to see your argument here.

i guess i was considering the case where you're not building notcurses with c++, but *do* have a c++ compiler. but let me look at this again and see about merging it (finally).

**Comment by dankamongmen** [comment]
let's see if we can bring it current really quickly...

**Comment by dankamongmen** [comment]
Thanks for your contribution to Notcurses!

**Pull request merged**
