### PR TITLE
Fix pip installation for cffi

### LINKED ISSUE #2391: Installation of cffi bindings with pip fails
Currently installing the package from pypi (`pip install notcurses`) fails with:
```
  ERROR: Command errored out with exit status 1:
   command: /home/mukundan/.local/share/asdf/installs/python/3.10.0/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9mw1147r
       cwd: /tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/
  Complete output (26 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/setup.py", line 35, in <module>
      setup(
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/dist.py", line 455, in __init__
      _Distribution.__init__(self, {
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/dist.py", line 807, in finalize_options
      ep(self)
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/.eggs/cffi-1.15.0-py3.10-linux-x86_64.egg/cffi/setuptools_ext.py", line 219, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/.eggs/cffi-1.15.0-py3.10-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/.eggs/cffi-1.15.0-py3.10-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
      exec(code, glob, glob)
    File "src/notcurses/build_notcurses.py", line 14, in <module>
      with open('../include/notcurses/notcurses.h') as fp:
  FileNotFoundError: [Errno 2] No such file or directory: '../include/notcurses/notcurses.h'
  warning: pypandoc module not found, won't generate man pages
```

This is probably due to the [sdist](https://pypi.org/project/notcurses/#files) currently uploaded to pypi not containing the include dir

I think this can probably be fixed by copying the `include` directory somewhere inside the `cffi` directory when setup.py is run by overriding `run` in `cmdclass` (similar to the what `ManPageGenerator` is doing) then including the copied directory in [`MANIFESTS.in`](https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands) and changing the `open(../include/notcurses/<header>.h)` lines to point to the location of the copied directory

### PR DESCRIPTION
**Pull request by Mukundan314**
Fixes #2391 

I consider this a pretty hacky solution but it seems to work for most cases

### CODE REVIEW

**Comment by dankamongmen** [comment]
I like it! I might have to change up some of the CI and even the packaging, but I'm sure I can make it work. Better I do that than everyone's pip fails. THANK YOU!

**Comment by dankamongmen** [comment]
so in the CI we're now hitting

```
    execfile(build_file_name, mod_vars)
  File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "src/notcurses/build_notcurses.py", line 14, in <module>
    with open('include/notcurses/notcurses.h') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'include/notcurses/notcurses.h'
Error: Process completed with exit code 1.
```

let me take a quick look

**Comment by dankamongmen** [comment]
it looks like with your new code i'd need run `python3 cffi/setup.py`? let me try that.

**Comment by dankamongmen** [comment]
i think if we do that, we'd need

`    cffi_modules=["cffi/src/notcurses/build_notcurses.py:ffibuild"],   `

in `setup.py`, and i'm not sure that'll work with your stuff...

**Comment by Mukundan314** [comment]
All testing i did was with `python setup.py` and not `python cffi/setup.py`

**Comment by Mukundan314** [comment]
It seems like i made some mistake working on a fix

**Comment by Mukundan314** [comment]
I think it should be fixed now

**Comment by dankamongmen** [comment]
> I think it should be fixed now

sweet, giving the CI another try

**Comment by dankamongmen** [comment]
woo-hooo! that's good enough for me! you are a champion!

**Pull request merged**
