### PR TITLE
mojibake: add emoji from unicode 14.0β

### PR DESCRIPTION
**Pull request by dankamongmen**
This adds the 37 new emoji from Unicode 14.0β to `mojibake`, though I don't think anything has support for them yet.

### CODE REVIEW

**Comment by dankamongmen** [comment]
there's nothing interesting here from a drawing perspective, sadly.

**Comment by dankamongmen** [comment]
ugh this really probably ought just use https://unicode.org/Public/emoji/14.0/emoji-test.txt

**Comment by michaelsbradleyjr** [comment]
From a somewhat under-informed would-be PR reviewer's perspective, could you add some advice how to web search re: `Unicode 14.0β`?

(so much I don't know 🤦 )

**Comment by michaelsbradleyjr** [comment]
nvm, I think I found a lead: https://www.unicode.org/versions/beta-14.0.0.html.

**Comment by dankamongmen** [comment]
h

> From a somewhat under-informed would-be PR reviewer's perspective, could you add some advice how to web search re: `Unicode 14.0β`?
> 
> (so much I don't know  )

i got there because i was thinking of sponsoring U+1F33F HERB 🌿 due to my love of U+1F33F HERB 🌿 + U+1F525 FIRE 🔥 -> U+1F574 MAN IN BUSINESS SUIT LEVITATING 🕴, and it had a link to the fancy new beta unicode.

https://unicode.org/emoji/charts-14.0/emoji-released.html#x1fab8
https://unicode.org/versions/Unicode14.0.0/

looks like they're targeting 2021-09-14 to drop

**Pull request merged**
