### PR TITLE
[workflows] delete ilmbase dependency in windows workflow

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
`ilmbase` is no longer offered:
* https://github.com/msys2/MINGW-packages/pull/12871#issuecomment-1235816186
* https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-ilmbase

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
The windows build is still failing, but now it's owing to `undefined reference` errors related to oiio.

**Comment by michaelsbradleyjr** [comment]
I tried switching back from Ninja to `-G"MSYS Makefiles"` and `make` to see if there would be any difference, but the errors were the same, so I killed that second commit in this PR branch.

**Comment by michaelsbradleyjr** [comment]
I found #2431 and it looked like the changes to switch to OpenImageIO's CMake support never got made, so I did so in 2bbbcdead2a906a1b522a93ab3010d1a06e99ab7. 

But the build still fails with `undefined reference` errors, so I was going to kill that commit in this PR and open another one with that change and hopefully a fix for the errors.

Anyway, apologies for the `[wip] ...` commit in the `master` branch; I should have switched the PR to draft before doing more experiments.

**Comment by dankamongmen** [comment]
it's no problem, but did we get things merged in the form you wanted?

**Comment by michaelsbradleyjr** [comment]
> it's no problem, but did we get things merged in the form you wanted?

Yes, the changes merged were/are good to go.

**Pull request merged**
