### PR TITLE
Invert the semantics of DECSDM

### LINKED ISSUE #2204: switch DECSDM default over
Most terminals I regularly work with have adapted to the true semantics of DECSDM (see #1782 and @j4james). we should probably go ahead and shift our default over, and track terminals which invert the "new" semantics.

i had already made the change for XTerm-369, though that change has not yet been released.

### PR DESCRIPTION
**Pull request by dankamongmen**
Drop the `tinfo` argument from `pixel_init()`, where it is not necessary. Drop `pixel_shutdown()`, which is no longer used. Consider the default DECSDM semantics to be enable-with-`80l` rather than `80h`. Invert the existing `invert_sixel` tests. Add a test for Alacritty 0.15.1, which follows the new semantics. Closes #2204.

### CODE REVIEW

**Comment by dankamongmen** [comment]
@j4james, i'd appreciate a quick look at this, if you can spare the time.

**Comment by dankamongmen** [comment]
tested with: mlterm 3.6.0, XTerm 369, alacritty 0.15.1, wezterm 20210922-215454-b19162b9, and foot 1.7.2. looks good.

**Comment by dankamongmen** [comment]
> tested with: mlterm 3.6.0, XTerm 369, alacritty 0.15.1, wezterm 20210922-215454-b19162b9, and foot 1.7.2. looks good.

also now tested with foot 1.8.2, looks good there, too.

**Comment by j4james** [comment]
Looks good to me. I've done some testing on the terminals I have, and my only issue was that the current version of Contour still uses the incorrect `DECSDM`, but it looks like you've already committed a fix for that.

I should also point out that the comments are a bit misleading, in that you're still confusing _Sixel Display Mode_, and _Sixel Scrolling_, which are the opposite of each other. You talk about "enabling DECSDM" with 80l, but that's not what is happening. When _Sixel Display Mode_ is enabled, images are rendered in the top left corner and clipped to the window. So when you _disable_ that mode (with 80l), images can then be rendered at any position, and scroll when they overflow the window.

I guess if it makes sense to you it doesn't really matter, but to an outsider it's rather confusing.

Also, this comment in `sixel_init_inverted` is now out of date:
https://github.com/dankamongmen/notcurses/blob/3136abca481f5f146758286111447ccaf280fa23/src/lib/sixel.c#L1057-L1058

**Comment by dankamongmen** [comment]
nah, that's why i asked. my understanding is flawed. i'll update it to reflect your comments; thanks much man!

**Comment by dankamongmen** [comment]
OHHHHHHHHHHHHHH ok it now all makes sense, and that's why it's called DECSDM, got it, very good, thank you!

**Comment by dankamongmen** [comment]
ok @j4james i think the current comments are correct. thanks a lot for looking them over!

**Comment by j4james** [comment]
Thanks. That's much better. But there's still one comment that mentions "enabling with \e[?80l" which I think is backwards (and I just realised it's also missing the `?` from that sequence):

https://github.com/dankamongmen/notcurses/blob/c5ab28acbd7407f9843cdc6ab8ec6258fefd1368/src/lib/termdesc.c#L46-L48

**Comment by dankamongmen** [comment]
> Thanks. That's much better. But there's still one comment that mentions "enabling with \e[?80l" which I think is backwards (and I just realised it's also missing the `?` from that sequence):

good catches, thanks! updated.

**Pull request merged**
