### PR TITLE
Added information about C standard to the CONTRIBUTING and change header file to be ISO C compliant

### PR DESCRIPTION
**Pull request by igo95862**
Probably useful for people who want to contribute C code.

### CODE REVIEW

**Comment by igo95862** [comment]
I also found that include files seems to contain the violations of ISO C. I am going to submit another PR with fixes.

**Comment by igo95862** [comment]
I only checked the `include/notcurses/` since it is what I compile my python modules with.

**Review by grendello — APPROVED** [review]

**Comment by igo95862** [comment]
Sec. Apparently there are big differences in how C and C++ handle `{0}` and `{ }`. I am going to include some `#ifdef`

**Comment by igo95862** [comment]
Basically this is the issue: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmissing-field-initializers

In C `{0]` is the empty initializer but in C++ `{}` is.

**Comment by dankamongmen** [comment]
Nice catch, thanks!

**Comment by dankamongmen** [comment]
Could we not just use explicit initialization and get rid of the #ifdefs, though? I'll go ahead and merge this but I think I'm going to change it to list the members and zero them all out. That'll work in both languages.

**Pull request merged**
