### PR TITLE
Rust compilation Fix 1 error and 2 warnings

### PR DESCRIPTION
**Pull request by tinmarino**
Hi,

I will try to play around notcurses, hopefully in Rust or Python but I must make this change for the Rust compilation to succeed.

Hope that helps.

### CODE REVIEW

**Comment by dankamongmen** [comment]
wooooooohoooo!

**Comment by dankamongmen** [comment]
thanks very much! this does indeed fix the compilation, so i'm going to merge it, though @joseluis might want to take a look

**Comment by joseluis** [comment]
thanks for the heads up @dankamongmen, I've had to update the function with the new expected return type.

**Comment by tinmarino** [comment]
That was incredibly fast!

Thank you guys, the project is awesome and is definitively improving terminal emulators, motivating dev to implement all xterm features (Sixels !).

All examples are working for me. I'll try to add dev some others like piano, calculator, 3d cube just to train.

@dankamongmen, you are right in the doc: TUI may really be usefull, in my case to spare the 2 minutes loging of x2go, the slow ping of ssh -X, the bugs and mantenance of java GUIs, the need for the client to install a program or get X-compliant and of course, as you said the bandwidth.

Awesome work!
Cheers.

**Comment by joseluis** [comment]
I'm glad you're playing with the rust wrappers @tinmarino, not many people are using them currently and they'll probably benefit from the attention.

> All examples are working for me. I'll try to add dev some others like piano, calculator, 3d cube just to train.

That would be absolutely fantastic. :exploding_head:

**Pull request merged**
