### PR TITLE
Workaround kitty F3 issue

### PR DESCRIPTION
**Pull request by neurocyte**
Notcurses does not recognize the F3 key correctly in kitty (and ghostty, maybe others?).

These are some workarounds I've had lying around in my local tree for a few months that resolve the issue for me. Really, really not sure about the quality and/or correctness of these fixes though. I have not spent too much time looking at the inner workings of the notcurses input layer and these changes are just enough to get it working for me.

Comments are very welcome.

### CODE REVIEW

**Comment by neurocyte** [comment]
This is a workaround/fix for https://github.com/dankamongmen/notcurses/issues/2720

**Comment by dankamongmen** [comment]
taking a look at it now (finally!), sorry about the lengthy delay

**Comment by dankamongmen** [comment]
wow, we sure don't pick up F3 correctly! good find

**Comment by dankamongmen** [comment]
verified in `notcurses-input` tip of `master`

**Comment by dankamongmen** [comment]
Merged via #2825. Thank you for your contribution to Notcurses!

**Pull request closed without merging**
