### PR TITLE
ci: run GHA workflow for macOS on all commits to master and PRs

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
Also split out the build of libqrcodegen on macOS into a separate step, and make the workflows for Ubuntu and macOS as consistent as possible; may require more changes depending on what passes and doesn't pass on macOS.

The GHA workflow for Windows will be revised in a separate PR.

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
@igo95862 the new python wrappers are failing to build on macOS. See: https://github.com/dankamongmen/notcurses/runs/3069269074?check_suite_focus=true.

Example error:
```
error: implicit conversion changes signedness: 'int' to 'unsigned int'
``` 

Is this something you could look into?

**Comment by michaelsbradleyjr** [comment]
@joseluis the rust wrappers are failing to build on macOS. See: https://github.com/dankamongmen/notcurses/runs/3069492019?check_suite_focus=true.

```
error[E0412]: cannot find type `_IO_FILE` in module `crate::ffi`
  --> src/file.rs:16:32
   |
16 | pub type FILE_NC = crate::ffi::_IO_FILE;
   |                                ^^^^^^^^ not found in `crate::ffi`
```

Is this something you could look into?

**Comment by igo95862** [comment]
@michaelsbradleyjr You can remove this line: https://github.com/dankamongmen/notcurses/blob/548ca72bf41c3d4909e2b4bc29e70ff5e6f761f1/python/setup.py#L24

It makes all warning errors. Looks like clang treats all bit manipulation on integers as conversions to unsigned integers. All the errors were in notcurses headers.

**Comment by joseluis** [comment]
> @joseluis the rust wrappers are failing to build on macOS. See: https://github.com/dankamongmen/notcurses/runs/3069492019?check_suite_focus=true.
> Is this something you could look into?

That should be fixed now. I've removed that part for now when compiling in macos in order to not cause problems.

**Comment by michaelsbradleyjr** [comment]
> That should be fixed now. I've removed that part for now when compiling in macos in order to not cause problems.

Looks like there's still one/more `NcFile` related thing to change: https://github.com/dankamongmen/notcurses/runs/3070337285?check_suite_focus=true.

```
error[E0412]: cannot find type `NcFile` in this scope
   --> src/notcurses/methods.rs:587:47
    |
587 |     pub fn render_to_file(&mut self, fp: &mut NcFile) -> NcResult<()> {
    |                                               ^^^^^^ help: a type alias with a similar name exists: `NcTime`
    | 
   ::: src/time.rs:6:1
    |
6   | pub type NcTime = crate::bindings::ffi::timespec;
    | ------------------------------------------------- similarly named type alias `NcTime` defined here
```

**Comment by michaelsbradleyjr** [comment]
> You can remove this line:
> https://github.com/dankamongmen/notcurses/blob/548ca72bf41c3d4909e2b4bc29e70ff5e6f761f1/python/setup.py#L24
> 
> It makes all warnings errors. Looks like clang treats all bit manipulation on integers as conversions to unsigned integers. All the errors were in notcurses headers.

That worked, though I ended up parameterizing in `python/setup.py` re: `platform`:

https://github.com/michaelsbradleyjr/notcurses/commit/32d8b081dcb34ab161059162bcb0072efc0a9bd7#diff-11a4a60b518bf24989d481468076e5d5982884626aed9faeb35b8576fcd223e1

There's an error when running `python/examples/000-print-version.py`: https://github.com/dankamongmen/notcurses/runs/3070256316?check_suite_focus=true.

```
ImportError: cannot import name 'notcurses_version' from 'notcurses'
```

**Comment by joseluis** [comment]
> Looks like there's still one/more `NcFile` related thing to change: https://github.com/dankamongmen/notcurses/runs/3070337285?check_suite_focus=true.

Ups, my bad! fixed

**Comment by michaelsbradleyjr** [comment]
> Ups, my bad! fixed

The rust tests compile and run now, but there's a problem when exiting the process: https://github.com/dankamongmen/notcurses/runs/3070761871?check_suite_focus=true.

```
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.61s

error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/runner/work/notcurses/notcurses/rust/target/debug/deps/libnotcurses_sys-ef15266bae1c14f7 --test-threads 1 --nocapture`
(signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by igo95862** [comment]
@michaelsbradleyjr The module does not compile properly without `--no-as-needed` passed to linker. For some reason it strips entire module of notcurses function calls.

https://github.com/dankamongmen/notcurses/blob/bc0ec7e68125ef3ad07e2b2a45910d47071f6f08/python/setup.py#L35

Not sure if clang supports this option but it should have something similar.

**Comment by joseluis** [comment]
> The rust tests compile and run now, but there's a problem when exiting the process

I've seen that before in local compilations, and it was some kind of compilation cache issue. Could you maybe try clearing the cargo cache of the build machine?

**Comment by michaelsbradleyjr** [comment]
> The module does not compile properly without `--no-as-needed` passed to linker. For some reason without it the linker strips entire module of notcurses function calls... Not sure if clang supports this option but it should have something similar.

`ld` on macOS doesn't have an `--no-as-needed` option, but it does have an `-all_load` option. I added a commit to check if that works, but currently the macOS build in GHA exits with error during `make`; see #1941.

**Comment by michaelsbradleyjr** [comment]
> I've seen that before in local compilations, and it was some kind of compilation cache issue. Could you maybe try clearing the cargo cache of the build machine?

It's failing in the macOS build in GitHub Actions, where there is no rust/cargo related cache, as far as I know.

**Comment by michaelsbradleyjr** [comment]
I rebased this PR branch to pick up the latest changes on `master`; *"python wrappers (new)"* now completes successfully, so `-all_load` did the trick (whether it's the best option to use, I'm not sure).

The only thing failing now is the *"rust wrappers"* step, where `cargo` fails to exit cleanly for an (as yet) unknown reason. I'll continue to investigate.

**Comment by michaelsbradleyjr** [comment]
@joseluis, a helpful person in the Rust community Discord suggested I try running with:
```
$ cargo +nightly miri test
```
For more info re: miri see: https://github.com/rust-lang/miri.

After getting setup locally with rustup, this is what I ran:
```
cargo +nightly miri test --no-fail-fast -- --test-threads 1 --nocapture
```

The output was extensive, so I put it in a gist: https://gist.github.com/michaelsbradleyjr/dffa41158e3305a55642ae4fc2c92702.

**Comment by igo95862** [comment]
I am not entirely sure why the `--no-as-needed`, `-all_load` is required. Might have something to do with how the project is linked.

**Comment by joseluis** [comment]
> @joseluis, a helpful person in the Rust community Discord suggested I try running with:
> 
> ```
> $ cargo +nightly miri test
> ```
> 

The bad thing is miri doesn't support calling FFI functions. I can disable the doc-tests for miri, that are failing in your build log, but then it fails with basic notcurses API functions that I can't disable because many functions depend on them...

```rust
running 43 tests
test cells::test::methods::constructors ... error: unsupported operation: can't call foreign function: notcurses_init
   --> src/notcurses/methods.rs:111:28
    |
111 |         let res = unsafe { notcurses_init(&options, null_mut()) };
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function: notcurses_init
    |
    = help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
```
I'm disabling the doc-tests for miri for now, and also disabled the bindgen layout tests since several was erroring because of detected UB (there's an open bindgen issue for that. Let's see if that helps anything.

**Comment by dankamongmen** [comment]
i must admit not paying close attention to this, but a quick recap suggests it's ready to go. is that accurate? it's not the case that everything needs to work on the builders right now, but it should pretty much be the solution you expect to go with.

**Comment by dankamongmen** [comment]
https://www.youtube.com/watch?v=fXZj4Wy58Pk

**Comment by dankamongmen** [comment]
> https://www.youtube.com/watch?v=fXZj4Wy58Pk

hrmm wait it's marked DRAFT and thus can't be merged. @michaelsbradleyjr , you have commit rights, don't you? chuck this bad boy in whenever it's ready to go. exciting!

**Comment by michaelsbradleyjr** [comment]
There's still one rust test failing on macOS after I rebased against `master`.

Locally I ran `$ RUST_BACKTRACE=full cargo t_all`. The output re: the failing test is in a gist: https://gist.github.com/michaelsbradleyjr/a9185a2f9075f9754b0bc8ebbf957556.

**Comment by joseluis** [comment]
> There's still one rust test failing on macOS after I rebased against `master`.

Thank! I'm gonna skip that test in macos for now

BTW, could you share with me the file at `target/debug/build/libnotcurses-sys-*/out/bindings.rs` so I can compare it with the one generated in x86_64 and dispel some doubts?

**Comment by michaelsbradleyjr** [comment]
All steps are passing now on macOS and Linux, time to merge it.

**Pull request merged**
