### PR TITLE
Feature/box

### PR DESCRIPTION
**Pull request by alexhsamuel**
A more Pythonic `box()` function.  WIP; putting this up for an initial reaction.

Departs from the C API as follows:
- one function that takes the box chars as args
- added `y`, `x` args for the upper left corner; moves cursor [questionable]
- doesn't expose cell
- exposes `fg` and `bg` separately instead of single `channels`; `rgb()` function for constructing 24-bit color values

Still several TODOs for this to be reasonable.

### CODE REVIEW

**Comment by dankamongmen** [comment]
I'd prefer behavior like cursor movement not be changed, if possible (it seems avoidable here--at worst, you can just do `ncplane_cursor_move_yx()` at the end). everything else seems totally reasonable.

**Comment by dankamongmen** [comment]
yeah, this is probably cleaner design than the C one. basically i needed EGC, colors, alpha, and style for the drawing characters, and overloaded `nccell` to get them across. taking those as arguments directly is cleaner (no concept of plane to which the cell is bound, no weird channel bit semantics).

**Comment by dankamongmen** [comment]
honestly, that's probably 99% of the uses of `nccell` in the API -- either passing or extracting EGC+color+alpha+style as a single object. it's debatable whether i ever ought have exposed it in the C API, but *Der Zug ist abgefahren*.

**Comment by alexhsamuel** [comment]
> I'd prefer behavior like cursor movement not be changed, if possible (it seems avoidable here--at worst, you can just do ncplane_cursor_move_yx() at the end). everything else seems totally reasonable.

OK, removed that.

I do think that many use cases will disable the visible cursor and just draw.  We might consider providing API variants with all coordinates explicit, to obviate the need for the user to track a state-y cursor that exists only in the imagination of the ncplane.  

Probably best to decide these things in the abstract and then apply them consistently to each entry point, rather than addressing each individually?  Where do you think is a good place to do this?  An issue?  Wiki? ...?

I'll start by checking out what other libraries do.

**Comment by dankamongmen** [comment]
is this ready to go? sorry, i've been away for a bit.

**Comment by alexhsamuel** [comment]
Yeah!  Do you want me to merge?

**Comment by dankamongmen** [comment]
please do!

sorry for the long delay; i was without a workstation for a month =\

**Comment by alexhsamuel** [comment]
A fate worse than death...

**Pull request merged**
